### ISSUE TITLE
kde+portal: files are not saved on the host

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak#1307]
If you try to save a file in `org.kde.kdenlive`, it always gets saved to `/run/user/1000/doc/.../file.kdenlive`. This works correctly with `org.kde.krita`, because krita seems to not use the standard file open dialog.

@grulja btw: is it okay to report these bugs here, or should I report them at bugs.kde.org?

**Comment by grulja** [comment]
I think this is correct, it should be saved at the correct location, but accessible through a document portal using /run/user/1000/doc/.../file.kdenlive.

**Comment by eszlari** [comment]
You mean this is correct behavior? How do I open a file from the file manager then? And now I noticed that the file is gone anyway after log out.

**Comment by grulja** [comment]
I just tried this now with Kate and it worked. I saved a new document to ~/foo.txt and while the path for Kate was /run/user/1000/doc/.../foo.txt, it was still saved to ~/foo.txt. It is just "exported" using document portal, because you actually don't have access from sandbox to your $HOME directory.

**Comment by eszlari** [comment]
> I just tried this now with Kate and it worked.

Have you tried it with kdenlive?

> because you actually don't have access from sandbox to your $HOME directory.

kdenlive has `--filesystem=host` in its manifest, so it should have access.

**Comment by grulja** [comment]
See https://github.com/flatpak/xdg-desktop-portal/issues/141.

**Comment by eszlari** [comment]
While kdenlive projects contain references to other files, at least the project file itself should get saved. Maybe these error messages that occur when selecting the "save file" or "open file" dialog in kdenlive are related (and that don't occur with Gtk apps):

```
Jan 15 18:08:45 localhost.localdomain xdg-desktop-por[2307]: Failed to reference external X11 window
Jan 15 18:08:45 localhost.localdomain xdg-desktop-por[2307]: Failed to associate portal window with parent window x11:33554451
Jan 15 18:08:45 localhost.localdomain xdg-desktop-por[2307]: '&ay' is not a valid GVariant format string
Jan 15 18:08:45 localhost.localdomain xdg-desktop-por[2307]: g_variant_get_va: assertion 'valid_format_string (format_string, !endptr, value)' failed
```

What looks buggy too is that the dialog is also named "Open", when saving.

**Comment by eszlari** [comment]
@grulja Can you reproduce this? I think the portal support should be reverted, until this is fixed, because it leaves a very bad impression of flatpak with users.

**Comment by eszlari** [comment]
Other apps I want to submit to flathub are also affected by this, so please, revert the portal support.

**Comment by eszlari** [comment]
And just found that like with https://github.com/flatpak/flatpak/issues/1276 -> when executing `rm /run/user/1000/flatpak-info` inside the sandbox, saving works. So this too is definitely caused by the portal support.

**Comment by eszlari** [comment]
New finding: saving works, if you use `xdg-desktop-portal-kde` in a KDE session. With `xdg-desktop-portal-gtk` it does not work (neither under KDE nor GNOME).

**Comment by nedrichards** [comment]
Just spoke briefly to @aleixpol on #flatpak IRC - they'd like us to report this upstream at: https://bugs.kde.org/enter_bug.cgi?product=xdg-desktop-portal-kde as well @eszlari can you do that? I think you've got the best handle on the actual issues.

**Comment by grulja** [comment]
There is no need to report this upstream, this has been already fixed in flatpak and xdg-desktop-portal.

**Comment by nedrichards** [comment]
Ah yes - it's this fix, right? https://github.com/flatpak/xdg-desktop-portal/commit/b660269ad8bfc008b4f25f00d89c07bccd09b447

@matthiasclasen do you know if there's anything blocking a portals release?

**Comment by grulja** [comment]
That's it, but it will be working only with latest flatpak which is not released yet.

**Comment by nedrichards** [comment]
@grulja is there no workaround until then? This makes using a lot of the apps that link against the KDE SDK close to uselesss for a lot of people. When an issue of this kind happened with Wayland we were able to disable that for apps until support was more widespread.

**Comment by grulja** [comment]
From my understanding this is only problem for apps like QtCreator, Kdenlive an so on where you manage multiple files/projects, if you open a file in Kate then this is not a problem at all. There is possible workaround where we can check inside sandbox whether the app has access to host's filesystem and in that case avoid using portal. I would still prefer not doing this and rely on xdg-desktop-portal but given this requires latest not released flatpak, we can take this approach. I'll try to do something about it once I find some time and let you know about it.

**Comment by nedrichards** [comment]
I haven't reproduced it yet myself but I think this KeepassXC bug is the same thing as well https://github.com/flathub/org.keepassxc.KeePassXC/issues/4

I totally agree with you about the unsatisfactoriness of workarounds but it's either that or revert the versions of all that stuff in the KDE SDK until people have a new enough version of Flatpak and the portals distributed.

**Comment by eszlari** [comment]
> From my understanding this is only problem for apps like QtCreator, Kdenlive

As I said above: saving in Kdenlive works when you're running KDE, but not GNOME!

> revert the versions of all that stuff in the KDE SDK until people have a new enough version of Flatpak and the portals distributed.

There are now two versions of the KDE SDK, 5.9 and 5.10. Why not simply revert portal support for 5.9 and leave on in 5.10 for testing?

**Comment by aleixpol** [comment]
> There are now two versions of the KDE SDK, 5.9 and 5.10. Why not simply revert portal support for 5.9 and leave it on in 5.10 for testing?

That wouldn't help, the bug is in the flatpak runtime. We need to make sure the fixed version reaches distributions.

**Comment by eszlari** [comment]
@alexlarsson According to https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule Ubuntu 18.04 LTS will have feature freeze on March 1st. Will there be another flatpak and xdg-desktop-portal release long enough before that to make it in? I think this is very important.

**Comment by nedrichards** [comment]
This was addressed in Flatpak 0.11.1 and 0.10.4 both released yesterday.

**Comment by eszlari** [comment]
I want to test this myself, when the update hits Fedora 27.

**Comment by eszlari** [comment]
@grulja I have tested this under Ubuntu 17.10 (Gnome) + flatpak PPA (flatpak 0.11.3 / xdg-desktop-portal 0.10) and it still does not work!

**Comment by grulja** [comment]
You are right, it is indeed broken, but I found out that the problem is in document-portal. I'm going to report it.

**Comment by grulja** [comment]
You need only the fix pushed to flatpak.

**Comment by eszlari** [comment]
@alexlarsson on April 19th is the final freeze for Ubuntu 18.04. Are you planing to release another version before? Maybe we could get this important fix still into the LTS version.

**Comment by nedrichards** [comment]
This fix should be present in Flatpak 0.11.4 released earlier today: https://github.com/flatpak/flatpak/releases/tag/0.11.4 can you test in that when available and close if required?

**Comment by eszlari** [comment]
I tested it, it's fixed.

**Comment by eladhen** [comment]
I'm sorry, I'm not a developer and I don't understand most of what you're talking about. I'm using Linux Mint 18.3 and I've got Kdenlive installed from flatpak and my saved project is locked in some folder I can't access outside of Kdenlive, and you seem to say this bug is fixed? I understand I shouldn't work with Kdenlive from flatpak anymore, but how can I get my project out of this place?

**Comment by eszlari** [comment]
I guess the file is lost but you can try this on the commandline:

```
$ flatpak --command=sh run org.kde.kdenlive
$ find / -name '*.kdenlive'
```
