### ISSUE TITLE
All the apps can not run after `flatpak update`

### ISSUE THREAD

**Issue by Honghe** [flatpak/flatpak#1359]
Environment:
* Ubuntu 16.04.3
* Flatpak 0.10.2.1

After `flatpak update` all the apps can not run. Such as Builder.

```
➜  ~ flatpak run org.gnome.Builder 
Can't find source path /run/user/1000/doc/by-app/org.gnome.Builder: No such file or directory
➜  ~ flatpak info org.gnome.Builder
Ref: app/org.gnome.Builder/x86_64/stable
ID: org.gnome.Builder
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-01-25 01:12:15 +0000
Subject: bump build (3f306ea1)
Commit: 268d5286c21417dedcf370a25fceeb5f67dce8a530cb35dee1b550ef4496e5e7
Parent: a18996581b27ed203c42a2739ad8ec5f2f4a3133ff8d235171270d59045ca8f8
Location: /var/lib/flatpak/app/org.gnome.Builder/x86_64/stable/268d5286c21417dedcf370a25fceeb5f67dce8a530cb35dee1b550ef4496e5e7
Installed size: 77.1 MB
Runtime: org.gnome.Sdk/x86_64/3.26
```
flatpub list
```
org.gnome.Glade/x86_64/stable                   user,current  
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 user,runtime  
org.freedesktop.Platform.ffmpeg/x86_64/1.6      user,runtime  
org.gnome.Platform/x86_64/3.26                  user,runtime  
org.gnome.Sdk.Docs/x86_64/3.26                  user,runtime  
org.gtk.Gtk3theme.Ambiance/x86_64/3.22          user,runtime  
org.gimp.GIMP/x86_64/stable                     system,current
org.gnome.Builder/x86_64/stable                 system,current
org.inkscape.Inkscape/x86_64/stable             system,current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6      system,runtime
org.freedesktop.Sdk/x86_64/1.6                  system,runtime
org.gnome.Platform/x86_64/3.24                  system,runtime
org.gnome.Sdk/x86_64/3.26                       system,runtime
org.gtk.Gtk3theme.Ambiance/x86_64/3.22          system,runtime
```
After reinstall the Builder, error again. 
journalctl
```
Jan 29 14:41:51 iron flatpak[8118]: libostree pull from 'flathub' for app/org.gnome.Builder/x86_64/stable complete
                                    security: GPG: summary+commit http: TLS
                                    delta: parts: 3 loose: 6
                                    transfer: secs: 99 size: 16.5 MB
Jan 29 14:42:01 iron gnome-session[3041]: (gnome-software:3206): As-WARNING **: failed to rescan: Failed to parse /var/lib/flatpak/exports/share/applications/org.gnome.Builder.desktop file: cannot process file of type application/x-desktop
Jan 29 14:42:23 iron flatpak[8118]: libostree pull from 'flathub' for runtime/org.gnome.Builder.Locale/x86_64/stable complete
                                    security: GPG: summary+commit http: TLS
                                    non-delta: meta: 2 content: 0
                                    transfer: secs: 22 size: 1.3 kB
Jan 29 14:42:28 iron smbd[8573]: pam_unix(samba:session): session closed for user nobody
Jan 29 14:42:28 iron flatpak[8118]: libostree pull from 'flathub' for runtime/org.gnome.Builder.Locale/x86_64/stable complete
                                    security: GPG: summary+commit http: TLS
                                    non-delta: meta: 3 content: 1
                                    transfer: secs: 5 size: 6.6 kB
Jan 29 14:42:31 iron smbd[8611]: pam_unix(samba:session): session closed for user nobody
```

**Comment by TingPing** [comment]
What are the logs from builder?

**Comment by Honghe** [comment]
@TingPing  
```
➜  ~ flatpak run -v org.gnome.Builder
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/honhe/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/honhe/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Allowing host-fs access
F: Allowing homedir access
F: skipping export for path /etc/ca-certificates
F: skipping export for path /etc/ssl
F: skipping export for path /etc/pki
F: Allowing x11 access
F: Allowing wayland access
Can't find source path /run/user/1000/doc/by-app/org.gnome.Builder: No such file or directory
➜  ~ flatpak list
Ref                                             Options       
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 user,runtime  
org.freedesktop.Platform.ffmpeg/x86_64/1.6      user,runtime  
org.gnome.Platform/x86_64/3.26                  user,runtime  
org.gnome.Sdk.Docs/x86_64/3.26                  user,runtime  
org.gtk.Gtk3theme.Ambiance/x86_64/3.22          user,runtime  
org.gimp.GIMP/x86_64/stable                     system,current
org.gnome.Builder/x86_64/stable                 system,current
org.gnome.Glade/x86_64/stable                   system,current
org.inkscape.Inkscape/x86_64/stable             system,current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6      system,runtime
org.freedesktop.Sdk/x86_64/1.6                  system,runtime
org.gnome.Platform/x86_64/3.24                  system,runtime
org.gnome.Platform/x86_64/3.26                  system,runtime
org.gnome.Sdk/x86_64/3.26                       system,runtime
org.gtk.Gtk3theme.Ambiance/x86_64/3.22          system,runtime

➜  ~ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           790M   40M  750M   6% /run
/dev/sda1       110G   95G  9.7G  91% /
tmpfs           3.9G  105M  3.8G   3% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop1       82M   82M     0 100% /snap/core/3887
/dev/loop2       84M   84M     0 100% /snap/core/3748
/dev/loop0      128M  128M     0 100% /snap/vscode/23
cgmfs           100K     0  100K   0% /run/cgmanager/fs
tmpfs           790M   12K  790M   1% /run/user/127
tmpfs           790M  132K  789M   1% /run/user/1000
```

**Comment by Honghe** [comment]
@TingPing What more log can I provide. I can not run any flatpak app now.

**Comment by alexlarsson** [comment]
I think the issue is that your document portal fuse mount got unmounted, but its not automatically mounted. Can you try killing all instances of xdg-document-portal and then run `fusermount -uz /run/user/1000/doc`

**Comment by Honghe** [comment]
It seems work.
```
➜  ps aux|grep xdg-document-portal                              
root     12233  0.0  0.0 572492   960 ?        Sl   Feb02   0:00 /usr/lib/flatpak/xdg-document-portal
honhe    28846  0.0  0.0  15960   976 pts/7    S+   17:36   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn xdg-document-portal
➜  sudo kill 12233
➜  fusermount -uz /run/user/1000/doc
fusermount: entry for /run/user/1000/doc not found in /etc/mtab
```

```
➜  cd /run/user/1000/doc 
➜  doc ll
total 0
dr-x------ 2 honhe honhe 0 Jan  1  1970 by-app
➜  doc tree
.
└── by-app
    └── org.gnome.Builder
```

```
➜  ~ flatpak list
Ref                                             Options       
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 user,runtime  
org.freedesktop.Platform.ffmpeg/x86_64/1.6      user,runtime  
org.gnome.Platform/x86_64/3.26                  user,runtime  
org.gnome.Sdk.Docs/x86_64/3.26                  user,runtime  
org.gtk.Gtk3theme.Ambiance/x86_64/3.22          user,runtime  
org.gimp.GIMP/x86_64/stable                     system,current
org.gnome.Builder/x86_64/stable                 system,current
org.gnome.Glade/x86_64/stable                   system,current
org.inkscape.Inkscape/x86_64/stable             system,current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6      system,runtime
org.freedesktop.Sdk/x86_64/1.6                  system,runtime
org.gnome.Platform/x86_64/3.24                  system,runtime
org.gnome.Platform/x86_64/3.26                  system,runtime
org.gnome.Sdk/x86_64/3.26                       system,runtime
org.gtk.Gtk3theme.Ambiance/x86_64/3.22          system,runtime

➜  ~ flatpak run -v org.gnome.Glade  
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/honhe/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/honhe/.local/share/flatpak
F: Disallowing network access
F: Allowing dri access
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing wayland access

(glade:2): Gtk-WARNING **: Content added to the action area of a dialog using header bars

(glade:2): Gtk-WARNING **: Content added to the action area of a dialog using header bars
GladeUI-Message: No DevHelp installed on your system, devhelp feature will be disabled.
GladeUI-Message: 1 missing displayable value for GtkWidget::events
GladeUI-Message: 1 missing displayable value for GtkWidget::AtkObject::accessible-role
GladeUI-Message: 2 missing displayable value for GtkEntry::input-hints
GladeUI-Message: No displayable values for property GtkMenu::anchor-hints
GladeUI-Message: 1 missing displayable value for GtkAboutDialog::license-type
GladeUI-Message: Glade needs artwork; a default icon will be used for the following classes:
	GThemedIcon	needs an icon named 'widget-gtk-themedicon'
	GtkApplicationWindow	needs an icon named 'widget-gtk-applicationwindow'

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(glade:2): GLib-GIO-CRITICAL **: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

➜  ~ flatpak run -v org.gnome.Builder
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/honhe/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/honhe/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Allowing host-fs access
F: Allowing homedir access
F: skipping export for path /etc/ca-certificates
F: skipping export for path /etc/ssl
F: skipping export for path /etc/pki
F: Allowing x11 access
F: Allowing wayland access
17:41:33.0039                                  GLib-GIO[    2]: CRITICAL: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
17:41:33.0040                                  GLib-GIO[    2]: CRITICAL: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
17:41:33.0040                                  GLib-GIO[    2]: CRITICAL: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
17:41:33.0040                                  GLib-GIO[    2]: CRITICAL: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
17:41:33.0040                                  GLib-GIO[    2]: CRITICAL: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
17:41:33.0040                                  GLib-GIO[    2]: CRITICAL: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

**Comment by alexlarsson** [comment]
So, it works now? 
I wonder why it was in a weird state though...

**Comment by Honghe** [comment]
@alexlarsson It works now. I have pasted the log on the last comment.

**Comment by mwleeds** [comment]
Closing this unless someone can reproduce on a recent version of flatpak

**Comment by divoxx** [comment]
I have also been seeing this issue

**Comment by divoxx** [comment]
This has been constantly happening to me. It works after a fresh boot but after while (potentially after sleeping, although I'm not sure), I can't launch any new applications with the following error:

`bwrap: Can't find source path /run/user/1000/doc/by-app/com.slack.Slack: No such file or directory`

The folder `/run/user/1000/doc/` is empty. What part of the system maintains that mount?

Let me know if I can provide any other information to help resolve this.

**Comment by TingPing** [comment]
@divoxx 	`xdg-document-portal` creates those directories and must have crashed or something. `env G_MESSAGES_DEBUG=all /usr/libexec/xdg-document-portal --replace --verbose` might fix it or show an error.

**Comment by divoxx** [comment]
@TingPing thanks, I manually ran `xdg-document-portal`with those flags and there has been no error logging and the process did not die but the same problem happened.

The entire output was:

```
$ env G_MESSAGES_DEBUG=all /usr/libexec/xdg-document-portal --replace --verbose
XDP: org.freedesktop.portal.Documents acquired
XDP: xdp_fuse_getattr 1 (fi=(nil))
XDP: xdp_fuse_getattr <- OK
```

I ran it yesterday, today when I tried to launch a program, the same problem happened but there was no additional output nor the process exit:

```
$ flatpak run com.spotify.Client
bwrap: Can't find source path /run/user/1000/doc/by-app/com.spotify.Client: No such file or directory
```

It also happened to all applications, so it's not specific to an application.

Should I open a separate issue?

**Comment by tallero** [comment]
I experienced the same problem when building programs in builder because xdg-document-portal systemd user service was not loaded in case someone has the same problem.

Has this service to be started at user login? Does it start when opening a flatpak app? So does it means that Builder has to load the service on distros that depend on systemd? Is it a distribution issue, a flatpak or builder issue?

**Comment by necrophcodr** [comment]
Been having this exact same issue with flatpak as well for more than 6 months, running Gentoo.

Running `fusermount -uz /run/user/1000/doc` resolves the issue, but it's not great having to do this.

The issue seems to occur after `flatpak update` _or_ after having had the computer suspended.

**Comment by divoxx** [comment]
@necrophcodr FYI I've created this other ticket related to that same exact issue: https://github.com/flatpak/xdg-desktop-portal/issues/305

**Comment by ploth** [comment]
Yep, same here with Gentoo (OpenRC).
`fusermount -uz /run/user/1000/doc` doesn't help, only gives `fusermount: entry for /run/user/1000/doc not found in /etc/mtab`.
What helps is killing the `/usr/libexec/xdg-document-portal` process.

**Comment by rugk** [comment]
Broke my installation too (Fedora 30):
```sh
$ flatpak run -v io.atom.Atom
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/rugk/.local/share/flatpak
F: Opening user flatpak installation at path /home/rugk/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/rugk/.local/share/flatpak
F: Cleaning up unused container id 1648328143
F: Allocated instance id 2442505132
F: Add defaults in dir /io/atom/Atom/
F: Add locks in dir /io/atom/Atom/
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/rugk/.config/pulse/client.conf': Error opening file /home/rugk/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 35 xdg-dbus-proxy --args=37'
F: Running 'bwrap --args 33 atom'
bwrap: Can't find source path /run/user/1000/.flatpak-helper/pkcs11-flatpak-6810: No such file or directory
```

This does not help:
```sh
$ env G_MESSAGES_DEBUG=all /usr/libexec/xdg-document-portal --replace --verbose
XDP: org.freedesktop.portal.Documents acquired
(/usr/libexec/xdg-document-portal:1516): GLib-DEBUG: 21:19:38.525: posix_spawn avoided (fd close requested) 
fusermount: entry for /run/user/1000/doc not found in /etc/mtab
XDP: xdp_fuse_getattr 1 (fi=(nil))
XDP: xdp_fuse_getattr <- OK
XDP: xdp_fuse_access 1 4
XDP: xdp_fuse_lookup 1/.Trash -> 
XDP: xdp_fuse_lookup <- error child ENOENT
XDP: xdp_fuse_lookup 1/.Trash-1000 -> 
XDP: xdp_fuse_lookup <- error child ENOENT
```

I see this in the logs for xdg:
![image](https://user-images.githubusercontent.com/11966684/57037324-2d54d680-6c57-11e9-951a-04d492eebb85.png)

![image](https://user-images.githubusercontent.com/11966684/57037491-9e948980-6c57-11e9-8e97-152f066d4142.png)

---


But for me, killing all `xdg–` things (permission store, document portal etc.) did _not_ help.

**Comment by Erick555** [comment]
I can reproduce this when using polyinstantiated `/tmp` and `/var/tmp` dirs through [pam_namespace](https://linux.die.net/man/8/pam_namespace) module. Running `xdg-document-portal --replace` fixes this issue for current session.

**Comment by elmarco** [comment]
same issue on my f30 laptop, I can't start Spotify anymore :( help welcome

**Comment by refi64** [comment]
I believe a workaround is `systemctl --user restart xdg-document-portal`, for anyone else stumbling upon this issue.

**Comment by matthiasclasen** [comment]
This should be fixed in xdg-desktop-portal master. The document portal will now exit when its fuse filesystem is unmounted from the outside

**Comment by Zorono** [comment]
Still happening on Flatpak 1.10.2 (Ubuntu 21.10)!!!!
$ **flatpak run org.telegram.desktop**
**bwrap: Can't find source path /run/user/1000/doc/by-app/org.telegram.desktop: Permission denied**

$ **flatpak run -v org.telegram.desktop**
```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/{USER}/.local/share/flatpak
F: Opening user flatpak installation at path /home/{USER}/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/org.telegram.desktop/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/{USER}/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2625187324
F: Allocated instance id 591660693
F: Add defaults in dir /org/telegram/desktop/
F: Add locks in dir /org/telegram/desktop/
F: Allowing host-fs access
F: skipping export for path /usr/libx32
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/{USER}/.config/pulse/client.conf': Error opening file /home/johnm/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 40 telegram-desktop'
bwrap: Can't find source path /run/user/1000/doc/by-app/org.telegram.desktop: Permission denied
```

$ **env G_MESSAGES_DEBUG=all /usr/libexec/xdg-document-portal --replace --verbose**
```
XDP: Providing portal org.freedesktop.portal.Documents
XDP: Providing portal org.freedesktop.portal.FileTransfer
XDP: org.freedesktop.portal.Documents acquired
XDP: INIT
XDP: ACCESS 1
XDP: GETATTR 1
XDP: LOOKUP 1:.Trash
XDP: LOOKUP -> error ENOENT
XDP: LOOKUP 1:.Trash-1000
XDP: LOOKUP -> error ENOENT
```

$ **ps aux|grep xdg-document-portal**
```
{USER}      76751  0.0  0.0  10324  2304 pts/0    S+   04:03   0:00 grep --color=auto xdg-document-portal
```

$ **fusermount -uz /run/user/1000/doc**
```
fusermount: entry for /run/user/1000/doc not found in /etc/mtab
```

$ **systemctl status --user xdg-document-portal**
```
× xdg-document-portal.service - flatpak document portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-document-portal.service; static)
     Active: failed (Result: exit-code) since Mon 2022-02-07 04:00:55 EET; 5min ago
    Process: 7328 ExecStart=/usr/libexec/xdg-document-portal (code=exited, status=20)
   Main PID: 7328 (code=exited, status=20)
        CPU: 680ms

Feb 07 01:04:53 {HOSTNAME} systemd[6668]: Starting flatpak document portal service...
Feb 07 01:04:54 {HOSTNAME} systemd[6668]: Started flatpak document portal service.
Feb 07 04:00:55 {HOSTNAME} systemd[6668]: xdg-document-portal.service: Main process exited, code=exited, status=20/n/a
Feb 07 04:00:55 {HOSTNAME} systemd[6668]: xdg-document-portal.service: Failed with result 'exit-code'.
```

**systemctl --user restart xdg-document-portal** didn't solve it for me :(

**Comment by vR4eslav** [comment]
same issue... wtf

when try to build:
`Application started at 22:52:20
bwrap: Can't find source path /run/user/1000/doc/by-app/org.vr4eslav.test_gtk: No such file or directory
Application exited
`

**Comment by tarbaII** [comment]
I caused this issue by unmounting all mounted volumes in GNOME Disks. Oops.

**Comment by Quix0r** [comment]
> same issue on my f30 laptop, I can't start Spotify anymore :( help welcome

It isn't a fix but you can try the `--no-documents-portal` switch but I guess that has other side-effects?
