### ISSUE TITLE
--env doesn't override XDG_DATA_HOME

### ISSUE THREAD

**Issue by bam80** [flatpak/flatpak#2413]
There is no way to change XDG_DATA_HOME environment variable value, other than manually, from within the container inself:
```
$ flatpak override --user --env=XDG_DATA_HOME=/home/bam/.local/share org.kde.discover
$ flatpak run --command=sh org.kde.discover                                                       
$ cat /.flatpak-info 
...
[Environment]
XDG_DATA_HOME=/home/bam/.local/share
...
$ echo $XDG_DATA_HOME
/home/bam/.var/app/org.kde.discover/data
```
Please, add it - I think the user should have such possibility if he really needs to change his variable inside the container.

@alexlarsson @aleixpol

**Comment by TingPing** [comment]
Sounds like you are trying to do something you shouldn't. The application can always override it at runtime.

**Comment by bam80** [comment]
This is the kind of variables the user should be able to change, not the application. Because it's _his_ variable.

**Comment by matthiasclasen** [comment]
In the case of XDG_*_HOME, flatpak is using these variables for its own purposes.

**Comment by kirbyfan64** [comment]
Do you have a more specific example than "some cases"?

**Comment by bam80** [comment]
Sure.
The org.kde.discover flatpak shares xdg-data with host.
So I need to have XDG_DATA_HOME in-sync with host just to make it work.

**Comment by matthiasclasen** [comment]
Flatpak makes certain assumptions and imposes certain restrictions. One of them is that we use XDG_DATA_HOME, XDG_CACHE_DIR, etc to point apps at their writable piece of filesystem space in ~/.var/app/$APPID

**Comment by bam80** [comment]
@matthiasclasen please explain how to make app working in the case I supplied then

**Comment by aleixpol** [comment]
It would make sense to at least rename the overriden variables into FLATPAK_* or something, in case we need to implement a wrapper.

**Comment by bam80** [comment]
@matthiasclasen use case is simple - Discover app should have access to a user-installed flatpaks in the host.
What adjustments would you suggest without even knowing the original host's XDG_DATA_HOME value?

**Comment by matthiasclasen** [comment]
I would suggest to just use $HOME/.local/share/flatpak. That is going to be right upwards of 95% of the time. For the 5 percent where it isn't, you can use FLATPAK_USER_DIR, maybe ?

**Comment by bam80** [comment]
We need a common solution which works in all cases, not relying on the percentages.
About FLATPAK_USER_DIR, I see it should be set by user again, but we still don't know host's XDG_DATA_HOME to do it.

**Comment by matthiasclasen** [comment]
I'm not suggesting that your application should set FLATPAK_USER_HOME.

You could consult FLATPAK_USER_HOME and use $HOME/.local/share/flatpak if it isn't set.

And yes, this will require the few users who insist on putting their flatpak user installation in a non-standard place to set an extra environment variable.

**Comment by bam80** [comment]
How would they know they are required to set FLATPAK_USER_HOME for this particular flatpak?
And no, they are still using standard place for flatpak because it's $XDG_DATA_HOME/flatpak

**Comment by matthiasclasen** [comment]
then I don't understand your problem at all

**Comment by kirbyfan64** [comment]
Could this whole thing basically be "provide a way to access the original host environment"? At least that's what I interpreted this as. 

@bam80 As a workaround you could just run `flatpak-spawn --host env` and grab the value from there, and add `--talk-name=org.freedesktop.Flatpak` to the permissions.

**Comment by bam80** [comment]
>Could this whole thing basically be "provide a way to access the original host environment"?

@kirbyfan64, you nailed it, I was going to open a separate issue for this (hoping it make sense to open an issues, still). I'll try your suggestion. Thanks

**Comment by TingPing** [comment]
It just a conceptual mismatch with Flatpak. It tries to be self-contained. Pretending its not and mixing host data with it is just a bad fit IMO.

**Comment by matthiasclasen** [comment]
well, we have well defined ways to make holes in the sandbox to accomodate that sort of thing.
just that we are using XDG_*_HOME for our own purposes, and thus can't easily let them in like this.

In retrospect, using XDG_DATA_HOME for the user repo location was probably a mistake. Should have just hardcoded $HOME/.local/share/flatpak

**Comment by matthiasclasen** [comment]
I think this was addressed now

**Comment by bam80** [comment]
Well, it still doesn't seem clear to me why we should override variables passed by `--env`, but at least original issue was addressed more directly in #2424, agree
