### ISSUE TITLE
apps can't connect to internet

### ISSUE THREAD

**Issue by Pshemas** [flatpak/flatpak#2921]
## Linux distribution and version
Opensuse Leap 15

## Flatpak version
1.0.5

## Description of the problem
Apps like Discord , Slack etc can't connect. On Steam I get invalid ssl certificate error. All from Flathub.
Getting a bit frustrated. First I was unable to install nvidia runtime (again Flathub's). Tested on 3 different workstations and 2 distros (SUSE 15 and Fedora 30) with 3 different net providers. Got TLS error.
Then I got a hint and downgraded all tls packages I could find to the basic ones found in the repos (3.6.2) and at least have been able to pull runtime (not sure downgrade did the trick or some libraries trickery - downgraded packages but haven't rebooted when pulled nvidia runtime). 
Now this... really no clue what happened to Flatpak recently. For over a year I've been super happy with it, but now it is getting to the point where it is unbearable. Tried searching the net for similar issue and found some other reports of TLS issues, but at this point I don't know whether the current problem is related or not.

**Comment by Pshemas** [comment]
it's even weirder. While on Steam I can't browse the store (SSL error) game update do download. But the Steam games (Dark Sould 3 via proton for example) report they can't connect to game server (worked without a hitch 2 weeks ago).
RSS reader fails to pull feeds from some of the sites. But not all. BBC loaded for example.
Discord and Slack fail outright.

**Comment by Pshemas** [comment]
ok, so it seems I got it working. Downgraded Flatpak (0.11.7)and Bubblewrap (0.2 at this point) and at this point it seems it made it work on Leap 15. No clue what to do with 15.1 .

**Comment by cho2** [comment]
## Linux distribution and version
openSUSE Tumbleweed

## Flatpak version
1.4.1

## Description of the problem
Some flatpak apps can't connect to the internet, i.e. Slack, Dropbox, Spotify. Some others can connect to the internet, i.e., Telegram.
I don't know what's the main problem.

**Comment by cho2** [comment]
@alexlarsson Any clue how to check this?

**Comment by Scartiloffista** [comment]
Same issue on an up-to-date Tumbleweed.

**Comment by cho2** [comment]
Anyway, my problem fixed with this https://bugzilla.suse.com/show_bug.cgi?id=1128358#c4

**Comment by refi64** [comment]
Hmm, could this be a bug in the resolv.conf monitoring?

**Comment by venekamp** [comment]
Without the proposed solution in https://bugzilla.suse.com/show_bug.cgi?id=1128358#c4  the problem still exists. However, after applying the proposed solution and restarting Networkmanager Slack, Riot, etc. are able to connect. Doing a reboot and having flatpaks start before Networkmanager has been able to setup the network also works. Only tried this once though.

**Comment by kryptt** [comment]
I have flatpak 1.4.3 on Gentoo and the workaround does not help, this was working fine up to a reboot after I upgraded to 1.4.3

**Comment by venekamp** [comment]
I am currently on flatpak 1.6.2 on openSUSE thumbleweed and have not seen the issue ever since applying the `rc-manager=symlink`.

This is my `/etc/NetworkManager/NetworkManager.conf`
```
[main]
plugins=keyfile
rc-manager=symlink

[connectivity]
uri=http://conncheck.opensuse.org
interval=0

[logging]
level=trace
```

**Comment by abread** [comment]
Spotify and Slack are also having trouble for me.
Using flatpak 1.6.2, but no networkmanager and a static resolv.conf (Gentoo with openrc and netifrc)

I noticed a (possibly unrelated) error message when opening Spotify: `/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)`

**Comment by kryptt** [comment]
My problem was actually related to a parallel p11-kit upgrade
https://github.com/flatpak/flatpak/issues/3388#issuecomment-597701441

**Comment by mercuriete** [comment]
@kryptt thanks
https://github.com/fosero/flatpak-overlay/issues/49

```
sudo emerge =p11-kit-0.23.20-r1 --ask --autounmask
```
worked for me on gentoo

(app affected was ```com.visualstudio.code```)

**Comment by hadess** [comment]
Closing, as this looks like an integration problem in distributions.
