### ISSUE TITLE
0.6.10 cannot install bundles without (optional in 0.6.9) repository metadata

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#314]
As of 0.6.10's release, users can no longer install bundles from https://download.mono-project.com/monodevelop/

The bundle build still runs fine  with 0.6.10, i.e. not passing `--repo-url=URL` does NOT fail `flatpak build-bundle`, which it ought to if this is now a mandatory flag.

```$ flatpak install --user --bundle monodevelop-6.1.0.5441.flatpak
error: No url for remote com.xamarin.Studio-origin specified```

**Comment by alexlarsson** [comment]
fixed

**Comment by xplicit** [comment]
is 0.6.11 version published with this bugfix? I still see 0.6.10 in launchpad https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

**Comment by directhex** [comment]
0.6.11 contains the fix, but isn't in the PPA yet. I'm running a locally updated package.

**Comment by alexlarsson** [comment]
I'll update the ppa when i'm back from the las gnome conference.

**Comment by dworzanski** [comment]
@alexlarsson I'm not sure if the management of the PPA is connected to the Debian repo, or if you're back from the conference yet, however if both of those are true, could you please update the Debian repo when you get a chance? I can't install MonoDevelop with an updated Debian 8 Jessie.

Thank you.

**Comment by directhex** [comment]
The Debian repo is mostly handled by @smcv by the look of it?

**Comment by alexlarsson** [comment]
I pushed updates for jessie today.
@smcv does the official packages for debian, which i mainly backport to xenial and jessie.
