### ISSUE TITLE
Failed to export bpf

### ISSUE THREAD

**Issue by MicrosoftTakeover** [flatpak/flatpak#3284]
## Linux distribution and version
NixOS 19.09
## Flatpak version
1.4.2
## Description of the problem
Running a flatpak application (com.discordapp.Discord) with a full disk results in the error `Failed to export bpf`

Let's consider checking for a full disk and providing a more descriptive error to alert the user of the problem.

**Comment by alexlarsson** [comment]
This is fixed via #3170

**Comment by JordanPlayz158** [comment]
This error still occurs if `/tmp` is full (if you wonder how that happened, currently, Plasma 6.1.1 seems to crash each time I unlock my lock screen or while screen locked, just today when I unlocked, there was like 9 and the `/tmp/drkonqi-*` filled up the 16GB of tmpfs at `/tmp`

**Comment by jefferyrlc** [comment]
Just ran into this. In my case it was due to the fact I run zram for swap and my swap was full, so it refused to run and gave me that error.
