### ISSUE TITLE
Apps are very small on high DPI screens; some GDK_* environment variables no longer respected?

### ISSUE THREAD

**Issue by Pointedstick** [flatpak/flatpak#3810]
## Linux distribution and version
openSUSE Tumbleweed with KDE Plasma 5.20

## Flatpak version
1.8.1

## Description of the problem
None of my GTK-based Flatpak apps are the right size anymore on my 4K screen with a 200% scale factor; they seem to be ignoring the GTK_* environment variables that determines the scale. This was working for a long time but regressed sometime recently.

Native GTK apps seem to get the right sizes for their widgets but the text is too small:

![Screenshot_20200821_083322](https://user-images.githubusercontent.com/1097249/90901970-fdb86900-e388-11ea-8bdf-8d7de012a0d8.jpeg)

For Electron apps, _everything_ is too small:

![Screenshot_20200821_083247](https://user-images.githubusercontent.com/1097249/90901904-e8433f00-e388-11ea-801f-752558156b53.jpeg)

## Steps to reproduce
1. Have a high DPI screen and set a global scale factor
2. Verify that the `GDK_DPI_SCALE` and `GDK_SCALE` environment variables are set in the environment, or set them yourself: `export GDK_DPI_SCALE=0.5; export GDK_SCALE=2`
3. Launch the app
4. Verify that these variables are set in the environment of of the app: <details><pre>cat /proc/`pidof gedit`/environ  | tr '\0' '\n'
SHELL=/bin/sh
SESSION_MANAGER=local/Liberator:@/tmp/.ICE-unix/1682,unix/Liberator:/tmp/.ICE-unix/1682
WINDOWID=153092103
QT_SCREEN_SCALE_FACTORS=eDP-1=2.5;DP-1=2.5;HDMI-1=2.5;DP-2=2.5;
COLORTERM=truecolor
XDG_CONFIG_DIRS=/app/etc/xdg:/etc/xdg
GDK_DPI_SCALE=0.5
LESS=-M -I -R
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
GTK_IM_MODULE=ibus
MACHTYPE=x86_64-suse-linux
G_BROKEN_FILENAMES=1
HOSTNAME=Liberator
HISTSIZE=1000
LANGUAGE=
FROM_HEADER=
MINICOM=-c on
QT4_IM_MODULE=xim
JAVA_ROOT=/usr/lib64/jvm/jre-openjdk
JAVA_HOME=/usr/lib64/jvm/jre-openjdk
AUDIODRIVER=pulseaudio
JRE_HOME=/usr/lib64/jvm/java-11-openjdk-11
SSH_AUTH_SOCK=/tmp/ssh-BywkjUtAxkVU/agent.1609
INPUT_METHOD=ibus
CPU=x86_64
SHELL_SESSION_ID=22ea16814bb9486981ab76d5329479b9
JAVA_BINDIR=/usr/lib64/jvm/jre-openjdk/bin
XMODIFIERS=@im=ibus
LIBVA_DRIVER_NAME=iHD
DESKTOP_SESSION=/usr/share/xsessions/plasmax11-dev
SSH_AGENT_PID=1611
GTK_RC_FILES=/etc/gtk/gtkrc:/home/nate/.gtkrc:/home/nate/.config/gtkrc
XCURSOR_SIZE=48
GPG_TTY=/dev/pts/2
EDITOR=vim
GTK_MODULES=canberra-gtk-module
XDG_SEAT=seat0
PWD=/home/nate
QEMU_AUDIO_DRV=pa
XDG_SESSION_DESKTOP=KDE
LOGNAME=nate
XDG_SESSION_TYPE=x11
MANPATH=/usr/local/man:/usr/local/share/man:/usr/share/man
XAUTHORITY=/run/user/1000/Xauthority
LS_OPTIONS=-N --color=tty -T 0
XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/nate/.gtkrc-2.0:/home/nate/.config/gtkrc-2.0
XNLSPATH=/usr/share/X11/nls
HOME=/home/nate
SSH_ASKPASS=/usr/lib/ssh/ssh-askpass
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=KDE
KONSOLE_DBUS_SERVICE=:1.99
PYTHONSTARTUP=/etc/pythonstart
KONSOLE_DBUS_SESSION=/Sessions/2
PROFILEHOME=
OSTYPE=linux
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
QT_IM_SWITCHER=imsw-multi
LESS_ADVANCED_PREPROCESSOR=no
KONSOLE_VERSION=201170
XSESSION_IS_UP=yes
KDE_SESSION_UID=1000
LESSCLOSE=lessclose.sh %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
G_FILENAME_ENCODING=@locale,UTF-8,ISO-8859-15,CP1252
HOST=Liberator
LESSOPEN=lessopen.sh %s
USER=nate
SDL_AUDIODRIVER=pulse
QT_QUICK_CONTROLS_STYLE_PATH=/home/nate/kde/usr/lib64/qml/QtQuick/Controls.2/:
COLORFGBG=15;0
PLASMA_USE_QT_SCALING=1
KDE_SESSION_VERSION=5
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
MORE=-sl
VISUAL=vim
CSHEDIT=emacs
DISPLAY=:99.0
SHLVL=2
WINDOWMANAGER=/home/nate/kde/usr/lib64/libexec/startplasma-dev.sh -x11
PAGER=less
MOZ_USE_XINPUT2=1
QT_IM_MODULE=ibus
CVS_RSH=ssh
XDG_VTNR=7
XDG_SESSION_ID=2
QML2_IMPORT_PATH=/home/nate/kde/usr/lib64/qml:
XDG_RUNTIME_DIR=/run/user/1000
QT_AUTO_SCREEN_SCALE_FACTOR=0
XCURSOR_THEME=breeze_cursors
XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share
KDE_FULL_SESSION=true
CONFIG_SITE=/usr/share/site/x86_64-unknown-linux-gnu
PATH=/app/bin:/usr/bin
GDK_SCALE=2
GTK_USE_PORTAL=1
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
PROFILEREAD=true
MAIL=/var/spool/mail/nate
HOSTTYPE=x86_64
QT_PLUGIN_PATH=/home/nate/kde/usr/lib64/plugins:
LESSKEY=/usr/etc/lesskey.bin
KONSOLE_DBUS_WINDOW=/Windows/1
_=/usr/bin/flatpak
GI_TYPELIB_PATH=/app/lib/girepository-1.0
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
FLATPAK_ID=org.gnome.gedit
PS1=[📦 $FLATPAK_ID \W]\$ 
FLATPAK_SANDBOX_DIR=/home/nate/.var/app/org.gnome.gedit/sandbox
XDG_DATA_HOME=/home/nate/.var/app/org.gnome.gedit/data
XDG_CONFIG_HOME=/home/nate/.var/app/org.gnome.gedit/config
XDG_CACHE_HOME=/home/nate/.var/app/org.gnome.gedit/cache
AT_SPI_BUS_ADDRESS=unix:path=/run/user/1000/at-spi-bus</pre></details>
5. Observe that the text in the app is too small (native GTK apps) or everything is too small (Electron apps)

**Comment by eszlari** [comment]
I guess a more future prove way to set scaling would be trough `xsettingsd`.

**Comment by refi64** [comment]
Is this still reproducible? I used these for quite some time without problems.

**Comment by Pointedstick** [comment]
It seems to have been fixed by something in the meantime. Perhaps https://bugs.kde.org/show_bug.cgi?id=438971

**Comment by shawny43** [comment]
Can we re-open again, it's seem not solved again! We have DPi Issue coming back after few years. Steam, Spotify, Discord and all others apps seem run in a problem including Emudeck. It's needs to be fixed. Im currently using Bazzite (An Fedora Ostree based) and Plasma 6. The issue still appearing.
