### ISSUE TITLE
[Bug]: Guix installation; flatpak search non-functional

### ISSUE THREAD

**Issue by thor314** [flatpak/flatpak#4626]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.1

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

GUIX Linux tk0 5.15.6 #1 SMP 1 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

Flatpak search appears to be non-functional, despite installation succeeding.

```
$ flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo 
$ flatpak search signal 
-> No matches found
$ flatpak install flathub org.signal.Signal
Looking for matches?
Required runtime for org.signal.Signal/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: y

org.signal.Signal permissions:
    ipc             network                 pulseaudio             x11
    devices         file access [1]         dbus access [2]        bus ownership [3]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures, xdg-public-share,
        xdg-videos
    [2] org.freedesktop.Notifications, org.freedesktop.portal.Background,
        org.kde.StatusNotifierWatcher
    [3] org.kde.*


        ID                                      Branch   Op   Remote    Download
 1. [?] org.freedesktop.Platform.GL.default     21.08    i    flathub   130.9?MB / 131.2?MB
 2. [?] org.freedesktop.Platform.Locale         21.08    i    flathub    17.7?kB / 325.0?MB
 3. [?] org.freedesktop.Platform.VAAPI.Intel    21.08    i    flathub    11.6?MB / 11.7?MB
 4. [?] org.freedesktop.Platform.openh264       2.0      i    flathub     1.5?MB / 1.5?MB
 5. [?] org.freedesktop.Platform                21.08    i    flathub   153.3?MB / 198.9?MB
 6. [?] org.signal.Signal                       stable   i    flathub   154.2?MB / 155.7?MB

Installation complete.
$ flatpak search signal
-> no matches found
$ flatpak list
Name                   Application ID                         Version  Branch  Installation
Freedesktop Platform   org.freedesktop.Platform               21.08.7  21.08   user
Mesa                   org.freedesktop.Platform.GL.default    21.3.1   21.08   user
Intel                  org.freedesktop.Platform.VAAPI.Intel            21.08   user
openh264               org.freedesktop.Platform.openh264      2.1.0    2.0     user
Signal Desktop         org.signal.Signal                      5.26.0   stable  user
```

### Expected Behavior

Results to appear on `flatpak search`

### Actual Behavior

No matches found

### Additional Information

I'm aware GUIX is not yet supported by flatpak. I'm hoping this issue is helpful in adding support.

**Comment by mwleeds** [comment]
You might want to report this bug against GUIX, unless it's clear the bug is in Flatpak and not the packaging done by GUIX?

**Comment by mwleeds** [comment]
You can try `flatpak update --appstream` as a workaround

**Comment by thor314** [comment]
does this error mean anything to you?
```
Error updating: No such metadata object c9a9887d2c7e15064c1f06bd19c28472cfcee96224f468863cd68bf6d8fc89d3.dirtree
```

**Comment by mwleeds** [comment]
> 

Looks like repo corruption, maybe related to #4412, you can try `flatpak --user repair`

**Comment by podiki** [comment]
I'm on GNU Guix and do not have this problem. @thor314 can you confirm that you are on a recent Guix version? Sounds like you are from the Flatpak version, which is when various bugs were fixed in packaging (though never had a problem with search before then either).

**Comment by Ashvith10** [comment]
This issue still exists on Guix. I am using `guix shell`, btw.

**Comment by Ashvith10** [comment]
I think I commented too soon, as the application started working afterwards. Just let it sit for a good few minutes.
