### ISSUE TITLE
eu-strip not taken from SDK

### ISSUE THREAD

**Issue by benwaffle** [flatpak/flatpak#648]
`eu-strip` is run from the host system, so in cases where it does not exist, it fails to build

For example, try building gnome-builder on a system without eu-strip available. You get `Failed to execute child process "eu-strip" (No such file or directory)`. But if you create a /bin/eu-strip program, it will run that

**Comment by alexlarsson** [comment]
This is a dependency of flatpak-builder, and if you don't have it that is a packaging bug. What build of flatpak do you use?

**Comment by alexlarsson** [comment]
(We can't in general have hard dependencies on what is in the SDK, so we can't rely on it being there)

**Comment by benwaffle** [comment]
I've fixed the packaging bug https://dev.solus-project.com/T2964

**Comment by Maziak2520** [comment]
Issue still there
stripping flatpak/org.gnome.Evolution-stable/files/lib/libical.so.3.0.3 to flatpak/org.gnome.Evolution-stable/files/lib/debug/lib/libical.so.3.0.3.debug
Error: module libical: Failed to execute child process "eu-strip" (No such file or directory)

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

sudo flatpak-builder --force-clean org.gnome.Evolution-stable org.gnome.Evolution-stable.json

**Comment by barthalion** [comment]
It's still a packaging bug @Maziak2520. Report it to Mint team (or Ubuntu).
