### ISSUE TITLE
Cannot build flatpak due to cache error

### ISSUE THREAD

**Issue by janbrummer** [flatpak/flatpak#818]
Creating a flatpak from within GNOME Builder for the second time results in:

```
Cache hit for cleanup, skipping
Cache hit for finish, skipping
Everything cached, checking out from cache
(flatpak-builder:16208): flatpak-ERROR **: Failed to check out cache: Fehler beim Entfernen der Datei »/home/jbrummer/.cache/gnome-builder/flatpak/staging/Roger-Router/flatpak:org.gnome.Platform-x86_64-3.24«: Directory not empty

```

```
[jbrummer@buzz-fedlet flatpak:org.gnome.Platform-x86_64-3.24]$ ls
files  metadata  var

```

So i guess instead of g_file_delete() g_remove() should be used in builder_cache_checkout.

**Comment by alexlarsson** [comment]
Hmm, flatpak-builder requires the directory you specify to not exist, or if you specify --force-clean it will be removed before starting. But this error seems different than that, its like it passed the check with the directory not existing, and then when it starts using it it now exists.

However, its kinda hard to tell, because there is very little information about what you did in the bug report.

**Comment by chergert** [comment]
I'm only seeing this when trying to activate our "Export Bundle" feature in Builder. And specifically when using the `Python` based `GNOME Application` template. It seems to work fine with `C`.

We don't want to `--force-clean` at this stage because we are trying to export the build (which we did our own incremental build so flatpak-builder does not have it cached).

I've extracted the command that is being run, and it looks like this:

```
[christian@starthink ~]$ flatpak-builder  --ccache --finish-only --repo /home/christian/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/repos/test-project/flatpak:org.gnome.Platform-x86_64-3.24 /home/christian/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/test-project/flatpak:org.gnome.Platform-x86_64-3.24 /home/christian/Projects/test-project/org.gnome.TestProject.json --force-clean 
Cache hit for cleanup, skipping
Cache hit for finish, skipping
Everything cached, checking out from cache

(flatpak-builder:4869): flatpak-ERROR **: Failed to check out cache: Error removing file /home/christian/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak/staging/test-project/flatpak:org.gnome.Platform-x86_64-3.24: Directory not empty
Trace/breakpoint trap (core dumped)
```

**Comment by janbrummer** [comment]
@alexlarsson, @chergert:
What kind of information do you need? I'm using GNOME Builder flatpak nightlys with the export bundle feature for a C project. It seems like the first run is fine, but every export afterwards fails due to this error. It could be fixed by replacing g_file_delete() g_remove() as described in my initial comment.

**Comment by chergert** [comment]
@janbrummer I'm not sure. I just tested with gnome-builder from git-master and I was able to build a Python GNOME Application template fine and export it to a .flatpak bundle. So perhaps this is fixed now?

**Comment by janbrummer** [comment]
No it is not fixed. As already mentioned i'm running the latest GNOME 
Builder Nightly flatpak building a C project.

Am Mo, 7. Aug, 2017 um 12:18 A. M. schrieb Christian Hergert 
<notifications@github.com>:

**Comment by chergert** [comment]
I was able to replicate with a C project if I exit Builder and reopen the project. The command being executed should resemble something like:

```sh
flatpak-builder \
  --ccache \
  --finish-only \
  --repo /home/christian/.cache/gnome-builder/flatpak/repos/test-project-2/flatpak:org.gnome.Platform-x86_64-master \
  /home/christian/.cache/gnome-builder/flatpak/staging/test-project-2/flatpak:org.gnome.Platform-x86_64-master \
  /home/christian/Projects/test-project-2/org.gnome.TestProject2.json
```

**Comment by janbrummer** [comment]
So where is the problem? Wrong usage of flatpak-builder in Builder or the opposite?

**Comment by chergert** [comment]
It's *probably* in Builder. I think after running build-finish operations, we essentially need to tear down our pipeline (or invalidate a good portion of it) before we allow ourselves to run any follow up commands.

**Comment by janbrummer** [comment]
Do you want an own Builder bug for this issue?

Am Di, 8. Aug, 2017 um 9:17 P. M. schrieb Christian Hergert 
<notifications@github.com>:

**Comment by chergert** [comment]
That'd be great, and link back here if you would. I'm doing some additional troubleshooting now that I got 3.25.90 out the door.

**Comment by janbrummer** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=786018

**Comment by chergert** [comment]
Fixed in Builder by switching from `flatpak-builder --finish-only` to manual control of `flatpak build-finish` and `flatpak build-export`.

**Comment by janbrummer** [comment]
Latest GNOME Builder fixes this issue for me. Issue can be closed
